#+title: Der Weg zur finanziellen Freiheit
#+subtitle: Ihre erste Million in 7 Jahren
#+author: Bodo Schäfer

* Wissen
- Geld bedeutet in erster Linie ein wesentlich freieres und unabhängigeres Leben führen zu können.
- Geld hat immer die Bedeutung, die wir ihm geben
- Selbstbewusst ist derjenige, der aufgrund von seiner Vergangenheit weiß, dass er sich auf sich selbst verlassen kann.
- Alle fünf Bereiche unseres Lebens müssen im Einklang stehen, denn wenn es in einem schmerzt leiden auch die anderen. (Finanzen, Beziehungen, Arbeit, Gesundheit, Emotionen)
- Was macht Spass und wie verdienst du damit Geld?
- Entweder sie planen ihr Leben oder andere verplanen es.
- Träume, Werte und Ziele müssen in einer Linie stehen.
- Reich macht nur das Geld, das wir behalten.
- Erfolg bedeutet zu bekommen was man will. Glück bedeutet das zu mögen was man bekommen hat.
- *Angewandtes* Wissen ist macht.
- Du bist immer verantwortlich für deine Reaktion.
- Wünsche sind Vorboten, wir entscheiden was wir uns wünschen und somit was wir haben  werden.
- Einkommen und Wortschatz korrelieren.
- Jeder erreicht seine eigenen Grenzen, egal wie hoch sie sind.
- Das Leben ist das Spiegelbild unserer Glaubenssätze.
- Wenn du Experte bist kommen die Kunden zu dir (#Positionierung)
- Der Weg des Cashflows zeigt ob es ein Investment oder eine Verbindlichkeit ist.
- Alles was wir über die Zukunft erzählen sind Märchen, also erzähle schöne Märchen.
* Können
- Wie kann ich eine Situation schaffen, dass dieses Problem nie wieder auftreten kann.
- Menschen nach Buchtipps fragen.
- Glaubenssätze auf ihren Nutzen hinterfragen und bei Bedarf ändern.
- Habe immer eine Cashreserve, denn die meisten finanziellen Probleme entstehen, weil man das nötige Kleingeld nicht hat.
- Spende Geld, denn wer Geld spendet der weiß, dass er mehr als genug hat.
